/var/spool/slurmd/job141770/slurm_script: line 8: ​: command not found
+ date
Wed Apr  6 11:27:05 EDT 2022
+ python hvss_bin_cmc.py

N2e5_rv0.5_rg2_Z0.0002, N=10 (2/148)
	Loading data...
	singles.shape:  (738637, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg2_Z0.0002, N=10 (3/148)
	Loading data...
	singles.shape:  (4687129, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg2_Z0.0002, N=10 (4/148)
	Loading data...
	singles.shape:  (1278067, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg2_Z0.0002, N=10 (5/148)
	Loading data...
	singles.shape:  (0, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg2_Z0.002, N=10 (6/148)
	Loading data...
	singles.shape:  (253201, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg2_Z0.002, N=10 (7/148)
	Loading data...
	singles.shape:  (352913, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg2_Z0.002, N=10 (8/148)
	Loading data...
	singles.shape:  (334265, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg2_Z0.002, N=10 (9/148)
	Loading data...
	singles.shape:  (404631, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg2_Z0.02, N=10 (10/148)
	Loading data...
	singles.shape:  (239409, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg2_Z0.02, N=10 (11/148)
	Loading data...
	singles.shape:  (215782, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg2_Z0.02, N=10 (12/148)
	Loading data...
	singles.shape:  (215228, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg2_Z0.02, N=10 (13/148)
	Loading data...
	singles.shape:  (424323, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg8_Z0.0002, N=10 (14/148)
	Loading data...
	singles.shape:  (1536336, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg8_Z0.0002, N=10 (15/148)
	Loading data...
	singles.shape:  (3090096, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg8_Z0.0002, N=10 (16/148)
	Loading data...
	singles.shape:  (1221225, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg8_Z0.0002, N=10 (17/148)
	Loading data...
	singles.shape:  (0, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg8_Z0.002, N=10 (18/148)
	Loading data...
	singles.shape:  (233435, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg8_Z0.002, N=10 (19/148)
	Loading data...
	singles.shape:  (270660, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg8_Z0.002, N=10 (20/148)
	Loading data...
	singles.shape:  (307449, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg8_Z0.002, N=10 (21/148)
	Loading data...
	singles.shape:  (354712, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg8_Z0.02, N=10 (22/148)
	Loading data...
	singles.shape:  (523994, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg8_Z0.02, N=10 (23/148)
	Loading data...
	singles.shape:  (118840, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg8_Z0.02, N=10 (24/148)
	Loading data...
	singles.shape:  (295176, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg8_Z0.02, N=10 (25/148)
	Loading data...
	singles.shape:  (456137, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg20_Z0.0002, N=10 (26/148)
	Loading data...
	singles.shape:  (1263157, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg20_Z0.0002, N=10 (27/148)
	Loading data...
	singles.shape:  (2258220, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg20_Z0.0002, N=10 (28/148)
	Loading data...
	singles.shape:  (1036679, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg20_Z0.0002, N=10 (29/148)
	Loading data...
	singles.shape:  (0, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg20_Z0.002, N=10 (30/148)
	Loading data...
	singles.shape:  (406750, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg20_Z0.002, N=10 (31/148)
	Loading data...
	singles.shape:  (576721, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg20_Z0.002, N=10 (32/148)
	Loading data...
	singles.shape:  (366108, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg20_Z0.002, N=10 (33/148)
	Loading data...
	singles.shape:  (400341, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv0.5_rg20_Z0.02, N=10 (34/148)
	Loading data...
	singles.shape:  (106877, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N4e5_rv0.5_rg20_Z0.02, N=10 (35/148)
	Loading data...
	singles.shape:  (109487, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N8e5_rv0.5_rg20_Z0.02, N=10 (36/148)
	Loading data...
	singles.shape:  (241346, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N1.6e6_rv0.5_rg20_Z0.02, N=10 (37/148)
	Loading data...
	singles.shape:  (381448, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=0.5 in [0.5 1.  2.  4. ]; found at index (array([0]),)

N2e5_rv1_rg2_Z0.0002, N=10 (38/148)
	Loading data...
	singles.shape:  (490349, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg2_Z0.0002, N=10 (39/148)
	Loading data...
	singles.shape:  (665136, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg2_Z0.0002, N=10 (40/148)
	Loading data...
	singles.shape:  (668089, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg2_Z0.0002, N=10 (41/148)
	Loading data...
	singles.shape:  (520205, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg2_Z0.002, N=10 (42/148)
	Loading data...
	singles.shape:  (230928, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg2_Z0.002, N=10 (43/148)
	Loading data...
	singles.shape:  (412299, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg2_Z0.002, N=10 (44/148)
	Loading data...
	singles.shape:  (408965, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg2_Z0.002, N=10 (45/148)
	Loading data...
	singles.shape:  (351189, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg2_Z0.02, N=10 (46/148)
	Loading data...
	singles.shape:  (55726, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg2_Z0.02, N=10 (47/148)
	Loading data...
	singles.shape:  (169411, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg2_Z0.02, N=10 (48/148)
	Loading data...
	singles.shape:  (136807, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg2_Z0.02, N=10 (49/148)
	Loading data...
	singles.shape:  (186192, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg8_Z0.0002, N=10 (50/148)
	Loading data...
	singles.shape:  (671802, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg8_Z0.0002, N=10 (51/148)
	Loading data...
	singles.shape:  (730528, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg8_Z0.0002, N=10 (52/148)
	Loading data...
	singles.shape:  (640784, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg8_Z0.0002, N=10 (53/148)
	Loading data...
	singles.shape:  (573566, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg8_Z0.002, N=10 (54/148)
	Loading data...
	singles.shape:  (241513, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg8_Z0.002, N=10 (55/148)
	Loading data...
	singles.shape:  (322488, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg8_Z0.002, N=10 (56/148)
	Loading data...
	singles.shape:  (427535, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg8_Z0.002, N=10 (57/148)
	Loading data...
	singles.shape:  (428326, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg8_Z0.02, N=10 (58/148)
	Loading data...
	singles.shape:  (79088, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg8_Z0.02, N=10 (59/148)
	Loading data...
	singles.shape:  (98452, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg8_Z0.02, N=10 (60/148)
	Loading data...
	singles.shape:  (132888, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg8_Z0.02, N=10 (61/148)
	Loading data...
	singles.shape:  (167866, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg20_Z0.0002, N=10 (62/148)
	Loading data...
	singles.shape:  (506193, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg20_Z0.0002, N=10 (63/148)
	Loading data...
	singles.shape:  (1867191, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg20_Z0.0002, N=10 (64/148)
	Loading data...
	singles.shape:  (616878, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg20_Z0.0002, N=10 (65/148)
	Loading data...
	singles.shape:  (573581, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg20_Z0.002, N=10 (66/148)
	Loading data...
	singles.shape:  (292630, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg20_Z0.002, N=10 (67/148)
	Loading data...
	singles.shape:  (391161, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg20_Z0.002, N=10 (68/148)
	Loading data...
	singles.shape:  (434536, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg20_Z0.002, N=10 (69/148)
	Loading data...
	singles.shape:  (436471, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv1_rg20_Z0.02, N=10 (70/148)
	Loading data...
	singles.shape:  (78985, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N4e5_rv1_rg20_Z0.02, N=10 (71/148)
	Loading data...
	singles.shape:  (92163, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N8e5_rv1_rg20_Z0.02, N=10 (72/148)
	Loading data...
	singles.shape:  (117647, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N1.6e6_rv1_rg20_Z0.02, N=10 (73/148)
	Loading data...
	singles.shape:  (213042, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N2e5_rv2_rg2_Z0.0002, N=10 (74/148)
	Loading data...
	singles.shape:  (685146, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg2_Z0.0002, N=10 (75/148)
	Loading data...
	singles.shape:  (706401, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg2_Z0.0002, N=10 (76/148)
	Loading data...
	singles.shape:  (693888, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg2_Z0.0002, N=10 (77/148)
	Loading data...
	singles.shape:  (538928, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg2_Z0.002, N=10 (78/148)
	Loading data...
	singles.shape:  (366015, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg2_Z0.002, N=10 (79/148)
	Loading data...
	singles.shape:  (620931, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg2_Z0.002, N=10 (80/148)
	Loading data...
	singles.shape:  (472790, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg2_Z0.002, N=10 (81/148)
	Loading data...
	singles.shape:  (455784, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg2_Z0.02, N=10 (82/148)
	Loading data...
	singles.shape:  (46299, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg2_Z0.02, N=10 (83/148)
	Loading data...
	singles.shape:  (57205, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg2_Z0.02, N=10 (84/148)
	Loading data...
	singles.shape:  (65045, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg2_Z0.02, N=10 (85/148)
	Loading data...
	singles.shape:  (89084, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg8_Z0.0002, N=10 (86/148)
	Loading data...
	singles.shape:  (527356, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg8_Z0.0002, N=10 (87/148)
	Loading data...
	singles.shape:  (742343, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg8_Z0.0002, N=10 (88/148)
	Loading data...
	singles.shape:  (696378, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg8_Z0.0002, N=10 (89/148)
	Loading data...
	singles.shape:  (488442, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg8_Z0.002, N=10 (90/148)
	Loading data...
	singles.shape:  (383500, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg8_Z0.002, N=10 (91/148)
	Loading data...
	singles.shape:  (478820, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg8_Z0.002, N=10 (92/148)
	Loading data...
	singles.shape:  (478321, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg8_Z0.002, N=10 (93/148)
	Loading data...
	singles.shape:  (481421, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg8_Z0.02, N=10 (94/148)
	Loading data...
	singles.shape:  (41602, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg8_Z0.02, N=10 (95/148)
	Loading data...
	singles.shape:  (54954, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg8_Z0.02, N=10 (96/148)
	Loading data...
	singles.shape:  (69512, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg8_Z0.02, N=10 (97/148)
	Loading data...
	singles.shape:  (86430, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg20_Z0.0002, N=10 (98/148)
	Loading data...
	singles.shape:  (577068, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg20_Z0.0002, N=10 (99/148)
	Loading data...
	singles.shape:  (642669, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg20_Z0.0002, N=10 (100/148)
	Loading data...
	singles.shape:  (654057, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg20_Z0.0002, N=10 (101/148)
	Loading data...
	singles.shape:  (477629, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg20_Z0.002, N=10 (102/148)
	Loading data...
	singles.shape:  (351909, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg20_Z0.002, N=10 (103/148)
	Loading data...
	singles.shape:  (489007, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg20_Z0.002, N=10 (104/148)
	Loading data...
	singles.shape:  (500759, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg20_Z0.002, N=10 (105/148)
	Loading data...
	singles.shape:  (482322, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv2_rg20_Z0.02, N=10 (106/148)
	Loading data...
	singles.shape:  (43772, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N4e5_rv2_rg20_Z0.02, N=10 (107/148)
	Loading data...
	singles.shape:  (50976, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N8e5_rv2_rg20_Z0.02, N=10 (108/148)
	Loading data...
	singles.shape:  (60554, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N1.6e6_rv2_rg20_Z0.02, N=10 (109/148)
	Loading data...
	singles.shape:  (89664, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N2e5_rv4_rg2_Z0.0002, N=10 (110/148)
	Loading data...
	singles.shape:  (286531, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg2_Z0.0002, N=10 (111/148)
	Loading data...
	singles.shape:  (496624, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg2_Z0.0002, N=10 (112/148)
	Loading data...
	singles.shape:  (493064, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg2_Z0.0002, N=10 (113/148)
	Loading data...
	singles.shape:  (492898, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg2_Z0.002, N=10 (114/148)
	Loading data...
	singles.shape:  (307698, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg2_Z0.002, N=10 (115/148)
	Loading data...
	singles.shape:  (361931, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg2_Z0.002, N=10 (116/148)
	Loading data...
	singles.shape:  (535173, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg2_Z0.002, N=10 (117/148)
	Loading data...
	singles.shape:  (520135, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg2_Z0.02, N=10 (118/148)
	Loading data...
	singles.shape:  (14871, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg2_Z0.02, N=10 (119/148)
	Loading data...
	singles.shape:  (28852, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg2_Z0.02, N=10 (120/148)
	Loading data...
	singles.shape:  (37783, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg2_Z0.02, N=10 (121/148)
	Loading data...
	singles.shape:  (47600, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg8_Z0.0002, N=10 (122/148)
	Loading data...
	singles.shape:  (718479, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg8_Z0.0002, N=10 (123/148)
	Loading data...
	singles.shape:  (699500, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg8_Z0.0002, N=10 (124/148)
	Loading data...
	singles.shape:  (548625, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg8_Z0.0002, N=10 (125/148)
	Loading data...
	singles.shape:  (465882, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg8_Z0.002, N=10 (126/148)
	Loading data...
	singles.shape:  (479904, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg8_Z0.002, N=10 (127/148)
	Loading data...
	singles.shape:  (490529, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg8_Z0.002, N=10 (128/148)
	Loading data...
	singles.shape:  (588805, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg8_Z0.002, N=10 (129/148)
	Loading data...
	singles.shape:  (639428, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg8_Z0.02, N=10 (130/148)
	Loading data...
	singles.shape:  (29233, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg8_Z0.02, N=10 (131/148)
	Loading data...
	singles.shape:  (32554, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg8_Z0.02, N=10 (132/148)
	Loading data...
	singles.shape:  (36103, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg8_Z0.02, N=10 (133/148)
	Loading data...
	singles.shape:  (51358, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg20_Z0.0002, N=10 (134/148)
	Loading data...
	singles.shape:  (553282, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg20_Z0.0002, N=10 (135/148)
	Loading data...
	singles.shape:  (627587, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg20_Z0.0002, N=10 (136/148)
	Loading data...
	singles.shape:  (553301, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg20_Z0.0002, N=10 (137/148)
	Loading data...
	singles.shape:  (532921, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg20_Z0.002, N=10 (138/148)
	Loading data...
	singles.shape:  (442042, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg20_Z0.002, N=10 (139/148)
	Loading data...
	singles.shape:  (576079, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg20_Z0.002, N=10 (140/148)
	Loading data...
	singles.shape:  (517124, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg20_Z0.002, N=10 (141/148)
	Loading data...
	singles.shape:  (497258, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N2e5_rv4_rg20_Z0.02, N=10 (142/148)
	Loading data...
	singles.shape:  (33190, 32)
	Binning data...
	Looking for N=2.0 in [ 2.  4.  8. 16. 32.]; found at index (array([0]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N4e5_rv4_rg20_Z0.02, N=10 (143/148)
	Loading data...
	singles.shape:  (32013, 32)
	Binning data...
	Looking for N=4.0 in [ 2.  4.  8. 16. 32.]; found at index (array([1]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N8e5_rv4_rg20_Z0.02, N=10 (144/148)
	Loading data...
	singles.shape:  (36501, 32)
	Binning data...
	Looking for N=8.0 in [ 2.  4.  8. 16. 32.]; found at index (array([2]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N1.6e6_rv4_rg20_Z0.02, N=10 (145/148)
	Loading data...
	singles.shape:  (45576, 32)
	Binning data...
	Looking for N=16.0 in [ 2.  4.  8. 16. 32.]; found at index (array([3]),)
	Looking for rv=4.0 in [0.5 1.  2.  4. ]; found at index (array([3]),)

N3.2e6_rv1_rg20_Z0.0002, N=10 (146/148)
	Loading data...
	singles.shape:  (403480, 32)
	Binning data...
	Looking for N=32.0 in [ 2.  4.  8. 16. 32.]; found at index (array([4]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N3.2e6_rv2_rg20_Z0.0002, N=10 (147/148)
	Loading data...
	singles.shape:  (348309, 32)
	Binning data...
	Looking for N=32.0 in [ 2.  4.  8. 16. 32.]; found at index (array([4]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

N3.2e6_rv1_rg20_Z0.02, N=10 (148/148)
	Loading data...
	singles.shape:  (144291, 32)
	Binning data...
	Looking for N=32.0 in [ 2.  4.  8. 16. 32.]; found at index (array([4]),)
	Looking for rv=1.0 in [0.5 1.  2.  4. ]; found at index (array([1]),)

N3.2e6_rv2_rg20_Z0.02, N=10 (149/148)
	Loading data...
	singles.shape:  (145735, 32)
	Binning data...
	Looking for N=32.0 in [ 2.  4.  8. 16. 32.]; found at index (array([4]),)
	Looking for rv=2.0 in [0.5 1.  2.  4. ]; found at index (array([2]),)

real	4m19.238s
user	3m26.777s
sys	0m44.193s
